data = [{'album_id_sp': '1s8iD2ldDPm79e3KRZmDuk',
  'album_tracks': [{'duration': 235199,
                    'spotify_id': '5Gul3AN3FLUePBf93Yd7QU',
                    'track_name': 'Своё заберу'},
                   {'duration': 207428,
                    'spotify_id': '14JceK2UBLd0UUm23N5lRy',
                    'track_name': 'Малый повзрослел'},
                   {'duration': 178143,
                    'spotify_id': '2UPXscs5RKYbzZ2eIv57C7',
                    'track_name': 'Маклауд'},
                   {'duration': 110082,
                    'spotify_id': '1aT5oQ7dMpCGasCl5154iP',
                    'track_name': 'Стилево'},
                   {'duration': 162505,
                    'spotify_id': '1BO1mdPpJr7EKJzDiicZMJ',
                    'track_name': 'Без косяка'},
                   {'duration': 268551,
                    'spotify_id': '6N34ZHkPTvEFTkyw5TKD6r',
                    'track_name': 'Крутой чел'},
                   {'duration': 229000,
                    'spotify_id': '3ygCMCP75yWNnR0nHBKWhx',
                    'track_name': 'Настоящий'},
                   {'duration': 206417,
                    'spotify_id': '5wTQSiqWdQc8aPh6IfwghU',
                    'track_name': 'Эмилия'},
                   {'duration': 213000,
                    'spotify_id': '47Cnb6vIqVwPvpv39CgYJJ',
                    'track_name': 'Мой друг'},
                   {'duration': 176000,
                    'spotify_id': '1tvVN54IT47bEI2vZxSZnY',
                    'track_name': 'Бессонница - Zest Remix'}],
  'artist_genres': ['belarusian hip hop', 'russian hip hop'],
  'artist_id_sp': '5meD8C7oGK5yUEY2T7ZZ7W',
  'artist_name': 'Max Korzh',
  'name_album': 'Малый повзрослел, Ч. 1',
  'release_date': '2016-11-28'},
 {'album_id_sp': '1MDptuCuxo8eE2Lfrxy3De',
  'album_tracks': [{'duration': 222840,
                    'spotify_id': '2eFP2s2etc9VSIPbLbynPd',
                    'track_name': 'I"ve Got The World On A String - New '
                                  'mono-to-stereo mix'},
                   {'duration': 157373,
                    'spotify_id': '4ZAG1a1wIHoPrANO3KKnsz',
                    'track_name': 'Stars Fell On Alabama - New mono-to-stereo '
                                  'mix'},
                   {'duration': 185218,
                    'spotify_id': '5NK4FQ3ePkYymu2l8nJk2D',
                    'track_name': 'Day In, Day Out - New mono-to-stereo mix'},
                   {'duration': 176053,
                    'spotify_id': '5oIM9ThaeNlggtaz7z4ZBN',
                    'track_name': 'Dancing On The Ceiling - New mono-to-stereo '
                                  'mix'},
                   {'duration': 181531,
                    'spotify_id': '4AHdceERdEtYgAt5bbrmpx',
                    'track_name': 'Accidents Will Happen - New mono-to-stereo '
                                  'mix'},
                   {'duration': 143313,
                    'spotify_id': '3QSQyj79aoRTO040m77bK8',
                    'track_name': 'At Long Last Love - New mono-to-stereo mix'},
                   {'duration': 179213,
                    'spotify_id': '3zS1XxIyJsx9HJfuhZ41CU',
                    'track_name': 'Blame It On My Youth - New mono-to-stereo '
                                  'mix'},
                   {'duration': 165786,
                    'spotify_id': '2AIMy6ekLc0kNo9gFRKzxB',
                    'track_name': 'April In Paris - New mono-to-stereo mix'},
                   {'duration': 195430,
                    'spotify_id': '1oc40VrGx7ojQg8HDixGHO',
                    'track_name': 'The Lady Is A Tramp - New mono-to-stereo '
                                  'mix'},
                   {'duration': 205519,
                    'spotify_id': '5MNc8uxzdgf05rAisGc4XB',
                    'track_name': 'I Couldn"t Sleep A Wink Last Night - New '
                                  'mono-to-stereo mix'},
                   {'duration': 160989,
                    'spotify_id': '7JMMRgG8KnYKPyPyOkc49z',
                    'track_name': 'One Finger Melody - New mono-to-stereo mix'},
                   {'duration': 179281,
                    'spotify_id': '6m99YtgGMbDD2hRHeKdvzx',
                    'track_name': 'I Cover The Waterfront - New mono-to-stereo '
                                  'mix'},
                   {'duration': 190906,
                    'spotify_id': '65aYTtEpMvwUK2z9QGJUlG',
                    'track_name': 'London By Night - New mono-to-stereo mix'},
                   {'duration': 148027,
                    'spotify_id': '15eMjMLaCbp9hHqBknSM6D',
                    'track_name': 'Too Marvelous For Words - New '
                                  'mono-to-stereo mix'},
                   {'duration': 175053,
                    'spotify_id': '4ErfPLSjhypS0c1lNaiO1l',
                    'track_name': 'Witchcraft - New mono-to-stereo mix'},
                   {'duration': 180488,
                    'spotify_id': '0LkJom23evvbXvOWSJONIb',
                    'track_name': 'In The Wee Small Hours - New mono-to-stereo '
                                  'mix'},
                   {'duration': 147226,
                    'spotify_id': '7AP55wHf5UZkkFqOmkozyH',
                    'track_name': 'My Girl - New mono-to-stereo mix'},
                   {'duration': 169122,
                    'spotify_id': '5VuKUnoVPiJs6AXqmL9Fr3',
                    'track_name': 'South Of The Border - New mono-to-stereo '
                                  'mix'},
                   {'duration': 147748,
                    'spotify_id': '5FKyHE71C1HJthMPLdM7oZ',
                    'track_name': 'You"ll Get Yours - New mono-to-stereo mix'},
                   {'duration': 133282,
                    'spotify_id': '18XsvdgRQmeNPTesnTzJ7p',
                    'track_name': 'Wrap Your Troubles In Dreams - New '
                                  'mono-to-stereo mix'}],
  'artist_genres': ['adult standards', 'easy listening', 'lounge'],
  'artist_id_sp': '1Mxqyy3pSjf8kZZL4QVxS0',
  'artist_name': 'Frank Sinatra',
  'name_album': 'Frank Sinatra - New Mono-To-Stereo Mixes',
  'release_date': '2022-03-22'},
 {'album_id_sp': '3upbeefzDw6XnmxB1e91fn',
  'album_tracks': [{'duration': 232973,
                    'spotify_id': '3eIAf2slHD2bKb8TYN2uHL',
                    'track_name': '...И корабль плывёт'},
                   {'duration': 233893,
                    'spotify_id': '19TAQ8y5nLULbJ33Me3yL0',
                    'track_name': 'Восток'},
                   {'duration': 310240,
                    'spotify_id': '49pJq809bZUY0jZUZNcMXb',
                    'track_name': 'Сердце'},
                   {'duration': 292800,
                    'spotify_id': '0J0kxm9USi4xWRrm6gIwTS',
                    'track_name': 'Мой друг'},
                   {'duration': 247866,
                    'spotify_id': '7FObYDrIosVLjDrvtcdSfs',
                    'track_name': 'Счастье'},
                   {'duration': 316400,
                    'spotify_id': '5HsvWZSIGKA2fFXklgmIkc',
                    'track_name': 'Никто не придёт'},
                   {'duration': 296293,
                    'spotify_id': '1mrqnd43bTOYYL4mv2ao5G',
                    'track_name': 'Полковнику никто не пишет'},
                   {'duration': 396200,
                    'spotify_id': '0Q2c2vh0FrQHfpnuegAaJ4',
                    'track_name': 'Деньги на ветер'},
                   {'duration': 352426,
                    'spotify_id': '2vUnDnUQREErxwXxqjoUkd',
                    'track_name': 'Медленно схожу с ума'},
                   {'duration': 302000,
                    'spotify_id': '0X8SJADiKzdNFXssPuLvrI',
                    'track_name': 'Варвара'},
                   {'duration': 275400,
                    'spotify_id': '7B0FDO2LgHbGVnkbDI92KH',
                    'track_name': 'Серебро'},
                   {'duration': 269613,
                    'spotify_id': '6VnqjZM16KYe5J0gjZA6ka',
                    'track_name': '…И корабль плывёт - Ernie O version'},
                   {'duration': 288893,
                    'spotify_id': '64enDjmcZHs7zTVKmmdusn',
                    'track_name': 'Варвара - Live'},
                   {'duration': 352346,
                    'spotify_id': '3BWGoHil8SoxT5FKwZy6gO',
                    'track_name': 'Медленно схожу с ума - Ernie O version'},
                   {'duration': 321160,
                    'spotify_id': '2cr9mGl2fxk4xUXJlfLvKo',
                    'track_name': 'Варвара - Ernie O Dance Remix'},
                   {'duration': 254106,
                    'spotify_id': '7E5L7NQTlinLFNqleyL8lg',
                    'track_name': 'Счастье - Ernie O version'},
                   {'duration': 262493,
                    'spotify_id': '7HTcKPm68pojKsh8Rbf0CJ',
                    'track_name': 'Серебро - Acoustic version'}],
  'artist_genres': ['belarusian pop',
                    'belarusian rock',
                    'classic russian rock',
                    'russian alternative rock',
                    'russian rock'],
  'artist_id_sp': '3SXDCIdqI1AR686ukKtKCq',
  'artist_name': 'Bi-2',
  'name_album': '...И корабль плывёт',
  'release_date': '2016-02-11'},
 {'album_id_sp': '7IE8ZTPWao2m1qNV744C4f',
  'album_tracks': [{'duration': 118356,
                    'spotify_id': '5ISgcj2vuSrL3FjHHnDPZU',
                    'track_name': 'Ты была права'}],
  'artist_genres': ['russian gangster rap', 'russian hip hop', 'russian pop'],
  'artist_id_sp': '7as5DY4Rz9jac9tgoTrj9H',
  'artist_name': 'Basta',
  'name_album': 'Ты была права',
  'release_date': '2021-06-07'},
 {'album_id_sp': '3iKJSrtfk7d5XjhfYp46RB',
  'album_tracks': [{'duration': 392412,
                    'spotify_id': '0GjFCJva3odJMfVPiwV4MI',
                    'track_name': 'Вспоминай меня'},
                   {'duration': 183144,
                    'spotify_id': '67TKC4FhlbpUvhuGwSgVq3',
                    'track_name': 'Молодость всё прощает'},
                   {'duration': 195532,
                    'spotify_id': '5BFADKJgtL2eZ4XZJq8zEc',
                    'track_name': 'Пьяный дождь'},
                   {'duration': 177626,
                    'spotify_id': '2fP2RBX81C55kEBaHZHomY',
                    'track_name': 'Малиновый закат'},
                   {'duration': 195272,
                    'spotify_id': '7a78yps1jTKGGGDpLlgThd',
                    'track_name': 'Оптимист'},
                   {'duration': 140188,
                    'spotify_id': '6td95tAD8bDAdz7o4jhNIv',
                    'track_name': 'Напалм'},
                   {'duration': 239910,
                    'spotify_id': '7f6ALwMTMLAhXCfoHYLCsx',
                    'track_name': 'Горы по колено'}],
  'artist_genres': ['belarusian hip hop', 'russian hip hop'],
  'artist_id_sp': '5meD8C7oGK5yUEY2T7ZZ7W',
  'artist_name': 'Max Korzh',
  'name_album': 'Малый повзрослел, Ч. 2',
  'release_date': '2017-10-27'},
 {'album_id_sp': '4ktDOYU0Jual1ELFTPhFd6',
  'album_tracks': [{'duration': 305275,
                    'spotify_id': '0wkFeB6P63PfJXZzYGxxnV',
                    'track_name': 'Здоровый сон'},
                   {'duration': 188240,
                    'spotify_id': '475G1r5398lgxVY7Ld7m8r',
                    'track_name': 'Стань'},
                   {'duration': 236878,
                    'spotify_id': '3tGcfXzjfMMKW4nZbfdD5H',
                    'track_name': 'Мотылёк'},
                   {'duration': 236571,
                    'spotify_id': '0HGjN29vI6V4HCveAAJGVu',
                    'track_name': 'За тобой'},
                   {'duration': 168831,
                    'spotify_id': '5qTsK1jrOC9V4QzjdoFywR',
                    'track_name': 'Эмигрант'},
                   {'duration': 246620,
                    'spotify_id': '4bGtP0H90r1ZRipMnb2HxJ',
                    'track_name': 'Тралики'},
                   {'duration': 174344,
                    'spotify_id': '2m3PVx1gsVB5upxi94IW8I',
                    'track_name': 'Жить в кайф'},
                   {'duration': 213222,
                    'spotify_id': '7iJGaleSuIK4cCmsUZyJli',
                    'track_name': 'Нет новостей'},
                   {'duration': 197362,
                    'spotify_id': '7AreTJOdh3mIDcBB1y6Ykd',
                    'track_name': 'Сеть'},
                   {'duration': 279379,
                    'spotify_id': '2PJXpGVRrm4qmdqUi7kc7a',
                    'track_name': 'Неважно'},
                   {'duration': 268906,
                    'spotify_id': '4GbHNkWtWUIZAL0owhoz1i',
                    'track_name': 'Эндорфин'},
                   {'duration': 206929,
                    'spotify_id': '2hEsbwkbs111QlIMPf6zHl',
                    'track_name': 'Тает дым'},
                   {'duration': 223261,
                    'spotify_id': '2ymLmKEZSIqW2WPcEYhwJC',
                    'track_name': 'Зелёный чемодан'},
                   {'duration': 290080,
                    'spotify_id': '7Muc3NFto30nGm9snUkvWs',
                    'track_name': 'Нет никаких правил'},
                   {'duration': 218444,
                    'spotify_id': '7qTNNLNMIUEImA7bbRHVbE',
                    'track_name': 'Время'},
                   {'duration': 198917,
                    'spotify_id': '5phKgCvKQqCP1cANb4ADzA',
                    'track_name': 'Неважно - Acoustic'},
                   {'duration': 202968,
                    'spotify_id': '1xEgzyi3SnbSwPLiFM4Ww3',
                    'track_name': 'Тает дым - DJ Nejtrino & DJ Baur Remix'}],
  'artist_genres': ['belarusian hip hop', 'russian hip hop'],
  'artist_id_sp': '5meD8C7oGK5yUEY2T7ZZ7W',
  'artist_name': 'Max Korzh',
  'name_album': 'Жить в кайф',
  'release_date': '2013-10-21'},
 {'album_id_sp': '5G5rgQHzdQnw32SI0WjIo5',
  'album_tracks': [{'duration': 6466,
                    'spotify_id': '2pjbf0b1yioklKVpjDKJwb',
                    'track_name': 'Intro'},
                   {'duration': 179466,
                    'spotify_id': '59q0gDvWPoL2DQ1SAt5ZLY',
                    'track_name': 'What Up Gangsta'},
                   {'duration': 288866,
                    'spotify_id': '6C781pluv3BPxGHHCUJNYc',
                    'track_name': 'Patiently Waiting'},
                   {'duration': 256240,
                    'spotify_id': '5STdMlrBf6pqWiNE7WqxSi',
                    'track_name': 'Many Men (Wish Death)'},
                   {'duration': 193466,
                    'spotify_id': '7iL6o9tox1zgHpKUfh9vuC',
                    'track_name': 'In Da Club'},
                   {'duration': 269360,
                    'spotify_id': '4Jp4T5gbCLQzGz545Jb3NY',
                    'track_name': 'High All The Time'},
                   {'duration': 254906,
                    'spotify_id': '1b4oehAiKqRh5uDMNJfz60',
                    'track_name': 'Heat'},
                   {'duration': 196626,
                    'spotify_id': '6mcu7D7QuABVwUGDwovOEh',
                    'track_name': 'If I Can"t'},
                   {'duration': 240000,
                    'spotify_id': '11hW1pk42xj0koCUJf9Xnj',
                    'track_name': 'Blood Hound'},
                   {'duration': 243000,
                    'spotify_id': '5HDRg2qrvX9qb6COeuDwfs',
                    'track_name': 'Back Down'},
                   {'duration': 249480,
                    'spotify_id': '3G0yz3DZn3lfraledmBCT0',
                    'track_name': 'P.I.M.P.'},
                   {'duration': 193253,
                    'spotify_id': '4ksfLHFX03oPI10oYgpO1R',
                    'track_name': 'Like My Style'},
                   {'duration': 199200,
                    'spotify_id': '1ZyZBoTB80BYCwHj56eyub',
                    'track_name': 'Poor Lil Rich'},
                   {'duration': 224440,
                    'spotify_id': '70FCugJxa7XW04Np6iYJdI',
                    'track_name': '21 Questions'},
                   {'duration': 248893,
                    'spotify_id': '7nh0HBrSbnmCfAraHcg7vK',
                    'track_name': 'Don"t Push Me'},
                   {'duration': 240666,
                    'spotify_id': '6KUcM0CPUSgbLyJbpukoBj',
                    'track_name': 'Gotta Make It To Heaven'},
                   {'duration': 219400,
                    'spotify_id': '2eXlwgFPe6HgFaPJO8xQHK',
                    'track_name': 'Wanksta - From "8 Mile" Soundtrack'},
                   {'duration': 255666,
                    'spotify_id': '0GltMgspY6OkEm4bBgsn8Z',
                    'track_name': 'U Not Like Me'},
                   {'duration': 218466,
                    'spotify_id': '4MwYBgpiNjmY42ak3mAh2o',
                    'track_name': 'Lifes On The Line'},
                   {'duration': 288573,
                    'spotify_id': '0fLILzjVXRCLC0lsNKcQ8I',
                    'track_name': 'P.I.M.P. - Snoop Dogg Remix'}],
  'artist_genres': ['east coast hip hop',
                    'gangster rap',
                    'hip hop',
                    'pop rap',
                    'queens hip hop',
                    'rap'],
  'artist_id_sp': '3q7HBObVc0L8jNeTe5Gofh',
  'artist_name': '50 Cent',
  'name_album': 'Get Rich Or Die Tryin',
  'release_date': '2003-02-06'},
 {'album_id_sp': '4CVaKIZ1zRUEFMgAKFZ4p3',
  'album_tracks': [{'duration': 182200,
                    'spotify_id': '2dpGc40PtSLEeNAGrTnJGI',
                    'track_name': 'Линия жизни'},
                   {'duration': 251466,
                    'spotify_id': '6JDpEs1XBGaPa6PjbM2zab',
                    'track_name': 'Звезда рок-н-ролла'},
                   {'duration': 181426,
                    'spotify_id': '3PA4LNNiaukTzYXM576fGc',
                    'track_name': 'Всего хорошего'},
                   {'duration': 249933,
                    'spotify_id': '5M3OJokRysqWyo1ewy8Yox',
                    'track_name': 'Моё сердце'},
                   {'duration': 120133,
                    'spotify_id': '6IJeVBxc4c4YwN3RBMlmAy',
                    'track_name': 'Рики-тики-тави'},
                   {'duration': 268506,
                    'spotify_id': '6jw9gmMI9dezT2rKFOH1C6',
                    'track_name': 'Sos!'},
                   {'duration': 286693,
                    'spotify_id': '7x5Xfl07ezxdJZmpJHQAQ3',
                    'track_name': 'Феллини'},
                   {'duration': 219640,
                    'spotify_id': '43wRpmuf20UPAZLAqooho5',
                    'track_name': 'Остаёмся зимовать'},
                   {'duration': 299400,
                    'spotify_id': '0Unq49Bogc5TmZdT9WJ4aC',
                    'track_name': 'Тебе это снится'},
                   {'duration': 131000,
                    'spotify_id': '4ihpgJBpbdtyURAZG9XM8w',
                    'track_name': 'Совсем другой'},
                   {'duration': 147560,
                    'spotify_id': '5TB5pBSEMJ0hJLqWXnkxmV',
                    'track_name': 'Пластмассовая жизнь'},
                   {'duration': 237573,
                    'spotify_id': '4v3n02NLIaFxJxBsCo49Ss',
                    'track_name': 'Пой мне ещё'},
                   {'duration': 156800,
                    'spotify_id': '6Pit3u2UJ960mOkzi8gaaS',
                    'track_name': 'Ленинград-амстердам'},
                   {'duration': 34666,
                    'spotify_id': '2aRtotT8Z4PPB3PBP5gxit',
                    'track_name': 'Fine'},
                   {'duration': 277133,
                    'spotify_id': '72CSGpraeQKqQo2vJ2T7of',
                    'track_name': 'P.S.феллини'}],
  'artist_genres': ['classic russian rock',
                    'russian alternative rock',
                    'russian rock'],
  'artist_id_sp': '6rdFMVoMSEN4GGX98u6QTj',
  'artist_name': 'Splean',
  'name_album': '25 кадр',
  'release_date': '2001'},
 {'album_id_sp': '6qxlSYECKCaNs3nnVBtnv5',
  'album_tracks': [{'duration': 103986,
                    'spotify_id': '6tEPhVSpnhWB9GebVl36be',
                    'track_name': 'Увертюра'},
                   {'duration': 150520,
                    'spotify_id': '6gffXll6PDkei4qEWnwWLe',
                    'track_name': 'Летела жизнь'},
                   {'duration': 166613,
                    'spotify_id': '1MUhnhGNqmW0BKULhtVSG0',
                    'track_name': 'Чёрная Волга'},
                   {'duration': 138666,
                    'spotify_id': '5lSv270jMbDX67FuM2hhCm',
                    'track_name': 'Лестница'},
                   {'duration': 144226,
                    'spotify_id': '027nG1nmEAUgJW44yVuGp3',
                    'track_name': 'Страшная тайна'},
                   {'duration': 260213,
                    'spotify_id': '3JCsB7IXDu8iQngFqoqgC7',
                    'track_name': 'Петербургская свадьба'},
                   {'duration': 216613,
                    'spotify_id': '7aOVkfwiNeX4ndOkvkxaYY',
                    'track_name': 'Дочь самурая'},
                   {'duration': 207826,
                    'spotify_id': '6Lxohp7UPGIEAIjNmFZNCM',
                    'track_name': 'Фибоначчи'},
                   {'duration': 178666,
                    'spotify_id': '5QJ4Q7k57UByKGG92CJzm9',
                    'track_name': 'В мире иллюзий'},
                   {'duration': 159946,
                    'spotify_id': '0iSXw6nsl0f1gFe1noAuAQ',
                    'track_name': 'Праздник - Другая точка зрения'},
                   {'duration': 180986,
                    'spotify_id': '7biQZ2RutmKWl5AcvdTcI9',
                    'track_name': 'Ковш'},
                   {'duration': 215040,
                    'spotify_id': '5oiijVaSCGGs6ZyUUkI8e6',
                    'track_name': 'Солнце взойдёт'},
                   {'duration': 149133,
                    'spotify_id': '4eyxQzQzWozclwxI9UCZzU',
                    'track_name': 'Чудак'},
                   {'duration': 264429,
                    'spotify_id': '2vtsSIod5LXxFH6z1KwjFg',
                    'track_name': 'Волшебное слово'}],
  'artist_genres': ['classic russian rock',
                    'russian alternative rock',
                    'russian rock'],
  'artist_id_sp': '6rdFMVoMSEN4GGX98u6QTj',
  'artist_name': 'Splean',
  'name_album': 'Обман зрения',
  'release_date': '2012-10-08'},
 {'album_id_sp': '0k6Jo1dGyZbOgGQcwUQ0QZ',
  'album_tracks': [{'duration': 206386,
                    'spotify_id': '03ZfZqyXvICBNpaEw9L0Wj',
                    'track_name': 'На часах ноль-ноль'}],
  'artist_genres': ['russian dance', 'russian pop'],
  'artist_id_sp': '1Uf3QoT2BwTN9ZW71cIiAo',
  'artist_name': 'Dabro',
  'name_album': 'На часах ноль-ноль',
  'release_date': '2021-05-14'},
 {'album_id_sp': '6i6folBtxKV28WX3msQ4FE',
  'album_tracks': [{'duration': 25186,
                    'spotify_id': '3YM9o7X3ar7Dm39zXadQSz',
                    'track_name': '20th Century Fox Fanfare'},
                   {'duration': 295733,
                    'spotify_id': '5txoZyuAmtCfmDjUCEphWm',
                    'track_name': 'Somebody To Love'},
                   {'duration': 196840,
                    'spotify_id': '69VE5kmfqG4dJSkrB1OtCI',
                    'track_name': 'Doing All Right - ...Revisited'},
                   {'duration': 236083,
                    'spotify_id': '34pz8XUZRfw04lk4DPtwa7',
                    'track_name': 'Keep Yourself Alive - Live At The Rainbow'},
                   {'duration': 179355,
                    'spotify_id': '300YN8ebGB90nDuzgz0f3O',
                    'track_name': 'Killer Queen'},
                   {'duration': 277706,
                    'spotify_id': '5Q2cQZKPvF4bpcjV3TCTss',
                    'track_name': 'Fat Bottomed Girls - Live In Paris'},
                   {'duration': 354947,
                    'spotify_id': '3z8h0TU7ReDPLIbEnYhWZb',
                    'track_name': 'Bohemian Rhapsody'},
                   {'duration': 265981,
                    'spotify_id': '4ysz5yttr3rpRkvyVMLlRB',
                    'track_name': 'Now I"m Here - Live At The Hammersmith '
                                  'Odeon'},
                   {'duration': 163342,
                    'spotify_id': '1F9NVicWfNQA5ki8WmEtk8',
                    'track_name': 'Crazy Little Thing Called Love'},
                   {'duration': 268703,
                    'spotify_id': '6Am82YdURCRXRvoVUObzzG',
                    'track_name': 'Love Of My Life - Live At Rock In Rio'},
                   {'duration': 129093,
                    'spotify_id': '2t8UoPFVXCRZulscbwv0QL',
                    'track_name': 'We Will Rock You - Movie Mix'},
                   {'duration': 214640,
                    'spotify_id': '2k1yPYf9WGA4LiqcLVwtzn',
                    'track_name': 'Another One Bites The Dust'},
                   {'duration': 223080,
                    'spotify_id': '7iAqvWLgZzXvH38lA06QZg',
                    'track_name': 'I Want To Break Free'},
                   {'duration': 244484,
                    'spotify_id': '6suU8oBlW4O2pg88tOXgHo',
                    'track_name': 'Under Pressure'},
                   {'duration': 314488,
                    'spotify_id': '77X4MKKCVpGSHsaErgCLzT',
                    'track_name': 'Who Wants To Live Forever'},
                   {'duration': 147840,
                    'spotify_id': '7xHATAMD7ezTZGYsNAMr5R',
                    'track_name': 'Bohemian Rhapsody - Live Aid'},
                   {'duration': 245680,
                    'spotify_id': '0YwBZKT8JE4U5TwmYE9BV9',
                    'track_name': 'Radio Ga Ga - Live Aid'},
                   {'duration': 41454,
                    'spotify_id': '6Fl9MoM9BDk6vwbHqBBZeK',
                    'track_name': 'Ay-Oh - Live Aid'},
                   {'duration': 243531,
                    'spotify_id': '5ekobRVHvm435Eipr1StAg',
                    'track_name': 'Hammer To Fall - Live Aid'},
                   {'duration': 237025,
                    'spotify_id': '4XaG9IpCXklOcuau1sIrUX',
                    'track_name': 'We Are The Champions - Live Aid'}],
  'artist_genres': ['classic rock', 'glam rock', 'rock'],
  'artist_id_sp': '1dfeR4HaWDbWqFHLkxsg1d',
  'artist_name': 'Queen',
  'name_album': 'Bohemian Rhapsody (The Original Soundtrack)',
  'release_date': '2018-10-19'},
 {'album_id_sp': '016FKucw479mVhXG8ZQvXD',
  'album_tracks': [{'duration': 160285,
                    'spotify_id': '4qGbCY0pWYZA4Lxa3umiI8',
                    'track_name': 'Друг или враг'},
                   {'duration': 187779,
                    'spotify_id': '1m8grmcdvw2FtflxAmCZ1B',
                    'track_name': 'Я весь мир обошёл'},
                   {'duration': 150738,
                    'spotify_id': '554lI5HqCoSWRAu87GrM3m',
                    'track_name': 'Нет твоей вины'},
                   {'duration': 163631,
                    'spotify_id': '5zyC3Ax8u1uJx44W4ATFLw',
                    'track_name': 'Техно'},
                   {'duration': 207770,
                    'spotify_id': '3wwAyTqjW4imvR9X1RJn2j',
                    'track_name': 'Я тебя сам придумал'},
                   {'duration': 147521,
                    'spotify_id': '1ijjbKJoXVNGTMVYO5k6ky',
                    'track_name': 'Такси'},
                   {'duration': 190273,
                    'spotify_id': '4CJ6EYGqcd8TdyNx9evu5i',
                    'track_name': 'Сигарета'}],
  'artist_genres': ['russian hip hop', 'russian pop'],
  'artist_id_sp': '6o7TsOGOEF5Mqpiz2KCyWE',
  'artist_name': 'HammAli & Navai',
  'name_album': 'Когда хорошему человеку плохо',
  'release_date': '2021-04-01'},
 {'album_id_sp': '28DUZ0itKISf2sr6hlseMy',
  'album_tracks': [{'duration': 184866,
                    'spotify_id': '49WLgjpFzrF2gCBZzWw1iv',
                    'track_name': 'Papercut'},
                   {'duration': 157333,
                    'spotify_id': '1qIQeMHFw09UjBpgrsrdys',
                    'track_name': 'One Step Closer'},
                   {'duration': 203266,
                    'spotify_id': '6NPVVeHetUBa6NhYSaMo1w',
                    'track_name': 'With You'},
                   {'duration': 200240,
                    'spotify_id': '0hSDsJ6OC0O4pih8jgT5m7',
                    'track_name': 'Points of Authority'},
                   {'duration': 208960,
                    'spotify_id': '1BfzeCKzo8xSvJcYLmnP8f',
                    'track_name': 'Crawling'},
                   {'duration': 183973,
                    'spotify_id': '3uO2ODjs7Lqp1DVZ4LtouE',
                    'track_name': 'Runaway'},
                   {'duration': 189800,
                    'spotify_id': '6mqhbwoBgTcw1lVqysIlTC',
                    'track_name': 'By Myself'},
                   {'duration': 216800,
                    'spotify_id': '6zyrb7dW1IR4Hrc8nXJsln',
                    'track_name': 'In the End'},
                   {'duration': 184640,
                    'spotify_id': '1c162st6mztGwnCllaJhcU',
                    'track_name': 'A Place for My Head'},
                   {'duration': 194426,
                    'spotify_id': '3QIPgdsvQpX6caei3iNJCe',
                    'track_name': 'Forgotten'},
                   {'duration': 157200,
                    'spotify_id': '0aOXvRZZJ2i874kZCvb7Z0',
                    'track_name': 'Cure for the Itch'},
                   {'duration': 191440,
                    'spotify_id': '4GQSDgwPgIswz5WvFp7ROO',
                    'track_name': 'Pushing Me Away'},
                   {'duration': 67560,
                    'spotify_id': '5crDbY4BQ6pDjYCfG1kyyj',
                    'track_name': 'Opening'},
                   {'duration': 225520,
                    'spotify_id': '6NDBZEa5nz6sy1CbCIrbe0',
                    'track_name': 'Pts.Of.Athrty - Jay Gordon Reanimation'},
                   {'duration': 239960,
                    'spotify_id': '7AicotfpDogKGfS6N5S3fF',
                    'track_name': 'Enth E Nd (Kutmasta Kurt Reanimation) '
                                  '[feat. Motion Man]'},
                   {'duration': 23746,
                    'spotify_id': '6Dh5GC7gUnOVzXBn6SKqly',
                    'track_name': '[Chali]'},
                   {'duration': 211520,
                    'spotify_id': '5Jq2dNGLV7MYp7JUc4Jega',
                    'track_name': 'Frgt/10 (Alchemist Reanimation) [feat. '
                                  'Chali 2na]'},
                   {'duration': 277973,
                    'spotify_id': '0NiLFbppboKW7fmsG1fKmF',
                    'track_name': 'P5hng Me A*wy (Mike Shinoda Reanimation) '
                                  '[feat. Stephen Richards]'},
                   {'duration': 260746,
                    'spotify_id': '3z4YazJkbpzlQCLFeeXrPi',
                    'track_name': 'Plc.4 Mie Hæd (Amp Live Reanimation) [feat. '
                                  'Zion]'},
                   {'duration': 109493,
                    'spotify_id': '46aLUOdBtEab6wAuMohYy9',
                    'track_name': 'X-Ecutioner Style (feat. Black Thought)'}],
  'artist_genres': ['alternative metal',
                    'nu metal',
                    'post-grunge',
                    'rap metal'],
  'artist_id_sp': '6XyY86QOPPrYVGvF9ch6wz',
  'artist_name': 'Linkin Park',
  'name_album': 'Hybrid Theory (20th Anniversary Edition)',
  'release_date': '2020-10-09'},
 {'album_id_sp': '1Rsrs1zDK4hznWYZhgOy7C',
  'album_tracks': [{'duration': 160054,
                    'spotify_id': '1VYW4KUIkTZiTrhW49CgCF',
                    'track_name': 'Ели мясо мужики'},
                   {'duration': 163685,
                    'spotify_id': '2crwcPC5a2x7pAHw0fPBCQ',
                    'track_name': 'Охотник'},
                   {'duration': 176766,
                    'spotify_id': '0Sj9sGwf7aYjPlS5bkqOmN',
                    'track_name': 'Отец и маски'},
                   {'duration': 188900,
                    'spotify_id': '3GOR8X3BQ2IuqnDsPI0s8E',
                    'track_name': 'Валет и дама'},
                   {'duration': 168812,
                    'spotify_id': '0FuPr947c9tk57g06vwZGk',
                    'track_name': 'Садовник'},
                   {'duration': 154500,
                    'spotify_id': '0b16TL8pn5b09UG2aWgjJ7',
                    'track_name': 'Холодное тело'},
                   {'duration': 147538,
                    'spotify_id': '7uqsckZun8NfxJbtT9IwdO',
                    'track_name': 'Леший обиделся'},
                   {'duration': 117433,
                    'spotify_id': '64BQlDdjOiOM72quSoDvNk',
                    'track_name': 'Дурак и молния'},
                   {'duration': 165433,
                    'spotify_id': '5ARZl38dswIeq0bMsTJe3H',
                    'track_name': 'Два вора и монета'},
                   {'duration': 120699,
                    'spotify_id': '1W8D60a8kg3yuoHABqMIgZ',
                    'track_name': 'Вячеслав'},
                   {'duration': 209140,
                    'spotify_id': '3kKOAnZTTaE0ptuXxeAc3D',
                    'track_name': 'Песня мушкетёров'},
                   {'duration': 182125,
                    'spotify_id': '0aSB6lak4W2ADZuZc0itM5',
                    'track_name': 'Весёлые тролли'},
                   {'duration': 182801,
                    'spotify_id': '0IZbRPugd7SGyF3WE5lLEt',
                    'track_name': 'Мария'},
                   {'duration': 82686,
                    'spotify_id': '4BnY5Fw0n4LNXQPqlcOlTo',
                    'track_name': 'Шар голубой'},
                   {'duration': 170513,
                    'spotify_id': '4YiBr6pEdOgKsMZzKhreV4',
                    'track_name': 'Мотоцикл'},
                   {'duration': 26913,
                    'spotify_id': '3Eb29Lv7IDllqfjbpMS2ht',
                    'track_name': 'Пьеса'},
                   {'duration': 196793,
                    'spotify_id': '3b5k4ogQbV8z0eZVMqMlwR',
                    'track_name': 'Прыгну со скалы'},
                   {'duration': 132896,
                    'spotify_id': '2J1H6wRDUwiYtP7O1hVeNw',
                    'track_name': 'Помоги мне!'},
                   {'duration': 136505,
                    'spotify_id': '3SSPr6ZYU1aQzkTF3oBzSK',
                    'track_name': 'Блуждают тени'},
                   {'duration': 109900,
                    'spotify_id': '4lxwutYvoXwoRfdZn9mBpO',
                    'track_name': 'Проказник скоморох'}],
  'artist_genres': ['classic russian rock',
                    'horror punk',
                    'russian folk rock',
                    'russian metal',
                    'russian punk',
                    'russian punk rock',
                    'russian rock',
                    'russian ska'],
  'artist_id_sp': '0qc4X567Fs1DUbQ7bS2XSJ',
  'artist_name': 'Korol i Shut',
  'name_album': 'Ели мясо мужики (Deluxe Edition)',
  'release_date': '2003-06-04'},
 {'album_id_sp': '1LoyJQVHPLHE3fCCS8Juek',
  'album_tracks': [{'duration': 322339,
                    'spotify_id': '2bPGTMB5sFfFYQ2YvSmup0',
                    'track_name': 'Deutschland'},
                   {'duration': 277397,
                    'spotify_id': '5vZ4IeUenK2cHub2d7yfWk',
                    'track_name': 'Radio'},
                   {'duration': 255845,
                    'spotify_id': '3d3k8g4GTVx9EFIFlOZOEX',
                    'track_name': 'Zeig dich'},
                   {'duration': 231603,
                    'spotify_id': '7j43FohbLVulScL7S9sQZk',
                    'track_name': 'Ausländer'},
                   {'duration': 236529,
                    'spotify_id': '15f16lrsDzFeNpHYBTzHLI',
                    'track_name': 'Sex'},
                   {'duration': 273706,
                    'spotify_id': '2iFgHPoa7FNHwgLnjXzu7F',
                    'track_name': 'Puppe'},
                   {'duration': 269045,
                    'spotify_id': '4anzVbFPUuZTw0KQeZ0qnu',
                    'track_name': 'Was ich liebe'},
                   {'duration': 154298,
                    'spotify_id': '1UZs9dauJnxrqYxMIzxnwC',
                    'track_name': 'Diamant'},
                   {'duration': 260915,
                    'spotify_id': '0sMmtnF7by7WPNeRXCam9H',
                    'track_name': 'Weit weg'},
                   {'duration': 251658,
                    'spotify_id': '6X5zsgjDlssIkv0sVYZgx1',
                    'track_name': 'Tattoo'},
                   {'duration': 251634,
                    'spotify_id': '2bHRnMtpXMUmzDHZrAyxne',
                    'track_name': 'Hallomann'}],
  'artist_genres': ['alternative metal',
                    'german metal',
                    'industrial',
                    'industrial metal',
                    'industrial rock',
                    'neue deutsche harte',
                    'nu metal'],
  'artist_id_sp': '6wWVKhxIU2cEi0K81v7HvP',
  'artist_name': 'Rammstein',
  'name_album': 'Rammstein',
  'release_date': '2019-05-17'},
 {'album_id_sp': '1Q9SnHWPNEjVM0LrBFvJ1q',
  'album_tracks': [{'duration': 165264,
                    'spotify_id': '0HqZX76SFLDz2aW8aiqi7G',
                    'track_name': 'Bones'}],
  'artist_genres': ['modern rock', 'rock'],
  'artist_id_sp': '53XhwfbYqKCa1cC15pYq2q',
  'artist_name': 'Imagine Dragons',
  'name_album': 'Bones',
  'release_date': '2022-03-11'}]
